# Generated by Django 5.1.6 on 2025-03-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="modelo",
            field=models.CharField(
                choices=[
                    ("Coseno", "Coseno"),
                    ("Pearson", "Pearson"),
                    ("Jaccard", "Jaccard"),
                ],
                max_length=32,
            ),
        ),
    ]
